
development:
  adapter: postgresql
  database: TeachOut_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: TeachOut_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: TeachOut_production
  pool: 5
  timeout: 5000
